package fr.mediaskol.projet.bo.formation;

import jakarta.persistence.*;
import lombok.AllArgsConstructor;
import lombok.Builder;
import lombok.Data;
import lombok.NoArgsConstructor;


// Génère un constructeur sans argument - Generates a constructor with no arguments.
@NoArgsConstructor
// Génère un constructeur avec un argument pour chaque champ - Generates a constructor with an argument for each field.
@AllArgsConstructor
@Data
@Builder

// Cette classe est une entité JPA persistée en base de données
// Nom de la table associée à cette entité dans la base de données
@Entity
@Table(name="FORMATION")
public class Formation {

    // Attributs - Attributes

    // clé primaire -- générée par la base avec IDENTITY - primary key -- generated by the database with IDENTITY
    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    @Column(name = "FORMATION_ID")
    private Long idFormation;

    // Thème de la formation
    @Column(name = "THEME_FORMATION", nullable = false, length = 20)
    private String themeFormation;


    // Thème de la formation
    @Column(name = "LIBELLE_FORMATION", nullable = false, length = 300)
    private String libelleFormation;


}
