package fr.mediaskol.projet.bo.formation;


import jakarta.persistence.*;
import lombok.AllArgsConstructor;
import lombok.Builder;
import lombok.Data;
import lombok.NoArgsConstructor;

// Génère un constructeur sans argument - Generates a constructor with no arguments.
@NoArgsConstructor
// Génère un constructeur avec un argument pour chaque champ - Generates a constructor with an argument for each field.
@AllArgsConstructor
@Data
@Builder

// Cette classe est une entité JPA persistée en base de données
// Nom de la table associée à cette entité dans la base de données
@Entity
@Table(name="TYPE_FORMATION")
public class TypeFormation {

    // Attributs - Attributes

    // clé primaire -- générée par la base avec IDENTITY - primary key -- generated by the database with IDENTITY
    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    @Column(name = "TYPE_FORMATION_ID")
    private Long idTypeFormation;

    // Thème de la formation
    @Column(name = "LIBELLE_TYPE_FORMATION", nullable = true, length = 300)
    private String libelleTypeFormation;
}
