package fr.mediaskol.projet.bo;

import jakarta.persistence.*;
import lombok.*;
import lombok.experimental.SuperBuilder;

import java.io.Serializable;

// Ajout du @Data de Lombok pour avoir les getter et les setter, toString, equals, hashCode
// Add Lombok's @Data to have getter and setter, toString, equals, hashCode for all fields.
@Data
// Génère un constructeur sans argument.
// Generates a constructor with no arguments.
@NoArgsConstructor
// Génère un constructeur avec un argument pour chaque champ.
// Generates a constructor with an argument for each field.
@AllArgsConstructor
// Facilite la mise en oeuvre du design pattern Builder
// Makes it easy to implement the Builder design pattern
@SuperBuilder

/** @Mélissa
 * Classe Business Object BO
 * Respecte le design pattern POJO (Plained Old Java Object)
 * Définie avec Lombok
 * Classe mère des entités Salarie, Formateur, Apprenant

 * Business Object BO class
 * Respects the POJO (Plained Old Java Object) design pattern
 * Defined with Lombok
 * Parent class for Salarie, Formateur and Apprenant entities
 */

// Cette classe est une entité JPA persistée en base de données
@Entity
// Nom de la table associée à cette entité dans la base de données
@Table(name = "PERSONNE")
/*
 * Définit la stratégie d’héritage JPA utilisée pour les sous-classes de Personne.
 * Ici, la stratégie JOINED signifie :
 *  - Une table PERSONNE contiendra les champs communs à toutes les personnes.
 *  - Chaque sous-classe (ex : Apprenant, Formateur, Salarié) aura sa propre table,
 *    reliée à PERSONNE par une clé étrangère (jointure).
 *  - Cette stratégie permet d’éviter la redondance de colonnes et de garder un modèle normalisé.
 */

// Déclaration de la classe de base pour toutes les personnes du système
// Héritage Joine en Spring Data JPA
@Inheritance(strategy = InheritanceType.JOINED)
public class Personne {

    // Attributs - Attributes

    // clé primaire -- générée par la base avec IDENTITY - primary key -- generated by the database with IDENTITY
    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    @Column(name = "PERSONNE_ID")
    private Long idPersonne;

    // Colonne non nulle - Non-zero column
    // Taille de la colonne en base 90 - Column size in base 90
    @Column(name="NOM", nullable = false, length = 90)
    private String nom;

    // Colonne non nulle - Non-zero column
    // Taille de la colonne en base 150 - Column size in base 150
    @Column(name="PRENOM", nullable = false, length = 150)
    private String prenom;

    // Colonne non nulle - Non-zero column
    // Taille de la colonne en base 255 - Column size in base 255
    // La valeur de l'email est unique - The value of email is unique
    @Column(name="EMAIL", nullable = false, unique = true, length = 255)
    private String email;

}
