package fr.mediaskol.projet.bo.salle;

// Ajout du @Data de Lombok pour avoir les getter et les setter, toString, equals, hashCode
// Add Lombok's @Data to have getter and setter, toString, equals, hashCode for all fields.

import fr.mediaskol.projet.bo.adresse.Adresse;
import jakarta.persistence.*;
import lombok.*;
import lombok.experimental.SuperBuilder;

// Génère un constructeur sans argument - Generates a constructor with no arguments.
@NoArgsConstructor
// Génère un constructeur avec un argument pour chaque champ - Generates a constructor with an argument for each field.
@AllArgsConstructor
@Getter
@Setter
// Pour avoir les données de l'Employé au ajoute le callsuper
@ToString(callSuper = true)
// Héritage Joined - Makes it easy to implement the Builder design pattern
@SuperBuilder

// Cette classe est une entité JPA persistée en base de données
// Nom de la table associée à cette entité dans la base de données
@Entity
@Table(name="SALLE")
public class Salle {

    // Attributs - Attributes

    // clé primaire -- générée par la base avec IDENTITY - primary key -- generated by the database with IDENTITY
    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    @Column(name = "SALLE_ID")
    private Long idSalle;

    // Nom de la salle de formation
    @Column(name = "NOM_SALLE", nullable = false, length = 255)
    private String nomSalle;

    // Nom du contact pour la salle
    @Column(name ="NOM_CONTACT", nullable = true, length = 200)
    private String nomContact;

    // Numéro du contact
    @Column(name="PORTABLE_CONTACT", nullable = true, length = 10)
    private String portableContact;

    // Adresse mail du contact
    @Column(name="MAIL_CONTACT", nullable=true, length = 255)
    private String mailContact;

    // Précise s'il y a besoin d'une clé 1 : oui  -  0 : non
    @Column(name="CLE_SALLE", nullable=false)
    private boolean cleSalle;

    // Numéro du digicode s'il y en a un
    @Column(name="DIGICODE_SALLE", nullable = true, length = 10)
    private String digiCodeSalle;

    // Commentaire qui indique diverses informations sur la salle en général
    @Column(name="COMMENTAIRE_SALLE", nullable = true, length = 2000)
    private String commentaireSalle;


    // Ajout de l'attribut adresse pour gérer l'association OneToOne
    // Association unidirectionnelle
    // Contrainte de composition - Les 2 entités ont le même cycle de vie (CascadeType.ALL)
    // Il faut que l'adresse devienne orpheline (orphanRemoval) et donc soit supprimée
    // Par défaut les 2 entités sont chargées
    @OneToOne(cascade = CascadeType.ALL, orphanRemoval = true, fetch = FetchType.EAGER)
    @JoinColumn(name="ADRESSE_ID")
    private Adresse adresse;
}
